name: webrtc_p2p_demo
description: A lightweight Flutter WebRTC demo app using QR-code/manual signaling without a backend.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_webrtc: ^1.4.1
  mobile_scanner: ^7.2.0
  qr_flutter: ^4.1.0
  share_plus: ^13.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
